[package]
name = "examples"
version = "0.1.0"
edition = "2024"
publish = false
autobins = true

[dependencies]
anyhow = "1"
apalis = { version = "1.0.0-rc.6", features = ["tracing"] }
serde = "1.0"
serde_json = "1"
tokio = { version = "1.45.0", features = ["full"] }
futures = "0.3"
apalis-postgres = "1.0.0-rc.6"
thiserror = "2.0.18"
apalis-file-storage = "0.1.0-rc.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio-util = { version = "0.7", features = ["codec"] }
bytes = "1"
